# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{http_utilities}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Johnsson"]
  s.date = %q{2011-07-09}
  s.description = %q{Wrapper for common Http Libraries (Net:HTTP/Open URI/Curl)}
  s.email = %q{sebastian@agiley.se}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "README",
    "Rakefile",
    "VERSION",
    "http_utilities.gemspec",
    "lib/generators/active_record/http_utilities_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/active_record/templates/proxy.rb",
    "lib/generators/helpers/file_helper.rb",
    "lib/generators/helpers/orm_helpers.rb",
    "lib/generators/http_utilities/http_utilities_generator.rb",
    "lib/generators/templates/http_utilities.rb",
    "lib/generators/templates/resque_schedule.yml",
    "lib/generators/templates/seed_data/proxies/http/public/L1/2011_04_11.txt",
    "lib/generators/templates/seed_data/proxies/http/public/L2/2011_04_11.txt",
    "lib/generators/templates/seed_data/proxies/http/public/L3/2010_08_18_1.txt",
    "lib/generators/templates/seed_data/proxies/http/public/unspecified/2011_04_11.txt",
    "lib/generators/templates/seed_data/proxies/socks5/public/2011_04_11.txt",
    "lib/generators/templates/user_agents.yml",
    "lib/http_utilities.rb",
    "lib/http_utilities/http/client.rb",
    "lib/http_utilities/http/cookies.rb",
    "lib/http_utilities/http/curb.rb",
    "lib/http_utilities/http/get.rb",
    "lib/http_utilities/http/net_http.rb",
    "lib/http_utilities/http/open_uri.rb",
    "lib/http_utilities/http/post.rb",
    "lib/http_utilities/http/proxy.rb",
    "lib/http_utilities/http/response_format.rb",
    "lib/http_utilities/jobs/proxies/check_proxies_job.rb",
    "lib/http_utilities/jobs/proxies/check_proxy_job.rb",
    "lib/http_utilities/proxies/proxy_checker.rb",
    "lib/http_utilities/proxies/proxy_module.rb",
    "lib/http_utilities/proxies/proxy_seeder.rb",
    "lib/http_utilities/railtie.rb",
    "lib/tasks/http_utilities_tasks.rake",
    "spec/database.yml.example",
    "spec/http_utilities/client_spec.rb",
    "spec/http_utilities/proxy_checker_spec.rb",
    "spec/http_utilities/proxy_seeder_spec.rb",
    "spec/http_utilities/proxy_spec.rb",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Agiley/http_utilities}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Wrapper for common Http Libraries (Net:HTTP/Open URI/Curl)}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord-import>, [">= 0"])
      s.add_runtime_dependency(%q<curb>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<generator_spec>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, ["= 0.2.7"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<activerecord-import>, [">= 0"])
      s.add_dependency(%q<curb>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<generator_spec>, [">= 0"])
      s.add_dependency(%q<mysql2>, ["= 0.2.7"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<activerecord-import>, [">= 0"])
    s.add_dependency(%q<curb>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<generator_spec>, [">= 0"])
    s.add_dependency(%q<mysql2>, ["= 0.2.7"])
  end
end

